apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: infra-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        role: web
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
