apiVersion: v1
kind: Service
metadata:
  name: was-service
  namespace: infra-practice
spec:
  selector:
    app: was
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
